# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/HTML-Embedded-Turtle/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" , "Test::RDF 0.23" ;
	:requires "Data::UUID", "RDF::RDFa::Parser 1.093", "common::sense" ,
		"RDF::Trine 0.135" , "RDF::TriN3" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/HTML/Embedded/Turtle.pm" .
